apiVersion: v1
kind: Namespace
metadata:
  name: moat-system
  labels:
    app.kubernetes.io/name: moat-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moat-operator
  namespace: moat-system
  labels:
    app.kubernetes.io/name: moat-operator
    app.kubernetes.io/component: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: moat-operator
      app.kubernetes.io/component: controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: moat-operator
        app.kubernetes.io/component: controller
    spec:
      serviceAccountName: moat-operator
      containers:
        - name: manager
          image: ghcr.io/example/moat-operator:latest
          imagePullPolicy: IfNotPresent
          args:
            - "--leader-elect"
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
