name: Continuous integration
on: [push, pull_request]

jobs:
  build:
    name: Build, test, check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache target
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/git/
            ~/.cargo/registry/
            target/
          key: ${{ runner.os }}-moat-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: ${{ runner.os }}-moat
      - name: Update toolchain
        run: rustup update stable && rustup default stable
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
